import { Document, Image, Page, StyleSheet, Text, View, pdf } from "@react-pdf/renderer";
import { VARIANT_LABEL, exportFilename, fitImageBox, scaleBarPoints, type ExportVariant } from "@/lib/map/map-export";

/**
 * Map PDF (map-system §12 / R2.5.15): the full-canvas capture + a title block + a true-scale
 * 50 ft bar. A4 landscape (842×595 pt). The layer set follows the current designer view —
 * enable Preview for the vendor lens before exporting.
 */

const PAGE_W = 842, MARGIN = 32, HEADER = 54, FOOTER = 40;

const styles = StyleSheet.create({
  page: { padding: MARGIN, fontFamily: "Helvetica", color: "#15120E" },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#01065B" },
  sub: { fontSize: 9, color: "#6B7280", marginTop: 3 },
  scaleRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 10 },
  bar: { height: 4, backgroundColor: "#01065B" },
  scaleLabel: { fontSize: 8, color: "#15120E" },
  footer: { position: "absolute", bottom: MARGIN, left: MARGIN, fontSize: 8, color: "#9CA3AF" },
});

interface DocProps { variant: ExportVariant; dataUrl: string; widthFt: number; heightFt: number; mapName: string; date: Date }

function MapPdfDoc({ variant, dataUrl, widthFt, heightFt, mapName, date }: DocProps) {
  const boxW = PAGE_W - MARGIN * 2;
  const boxH = 595 - MARGIN * 2 - HEADER - FOOTER;
  const img = fitImageBox(widthFt, heightFt, boxW, boxH);
  const bar = scaleBarPoints(widthFt, img.width, 50);
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View>
          <Text style={styles.title}>{VARIANT_LABEL[variant]}</Text>
          <Text style={styles.sub}>{mapName} · {date.toLocaleDateString("en-IN")} · {Math.round(widthFt)} × {Math.round(heightFt)} ft</Text>
        </View>
        {/* react-pdf primitive, not an HTML img — no alt attribute exists */}
        {/* eslint-disable-next-line jsx-a11y/alt-text */}
        <Image src={dataUrl} style={{ width: img.width, height: img.height, alignSelf: "center", marginTop: 10 }} />
        <View style={styles.scaleRow}>
          <View style={[styles.bar, { width: bar }]} />
          <Text style={styles.scaleLabel}>50 ft</Text>
        </View>
        <Text style={styles.footer}>Generated by BDQ Social · Map Designer</Text>
      </Page>
    </Document>
  );
}

export async function downloadMapPdf(
  variant: ExportVariant,
  cap: { dataUrl: string; widthFt: number; heightFt: number },
  mapName: string,
): Promise<void> {
  const date = new Date();
  const blob = await pdf(<MapPdfDoc variant={variant} dataUrl={cap.dataUrl} widthFt={cap.widthFt} heightFt={cap.heightFt} mapName={mapName} date={date} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = exportFilename(variant, mapName, date, "pdf"); a.click();
  URL.revokeObjectURL(url);
}
